export const SERVICE_DETAILS = [
  "Hepatobiliary appointment availability",
  "Hepatobiliary Consultation",
  "Laboratory tests (Screening)",
  "Ultrasound appointment availability",
  "Ultrasound procedure and report",
  "CT scan appointment availability",
  "CT Scan procedure and report",
  "Financial Screening assesment",
  "MRCP appointment availability",
  "MRCP procedure and report",
  "Laboratory tests (Rare Tests)",
  "PFT",
  "ECG",
  "ECHO",
  "Cardiology appointment availability",
  "Cardiology Consultation",
  "Pulmonology appointment availability",
  "Pulmonology Consultation",
  "Psychiatrist appointment availability",
  "Psychiatrist Consultation",
  "Anesthetist appointment availability",
  "Anesthetist Consultation",
  "Infectious Disease appointment availability",
  "Infectious Disease Consultation",
  "Gynecologist appointment availability",
  "Gynecologist Consultation",
  "Transplant Hepatology appointment availability",
  "Transplant Hepatology Consultation",
  "Listing Meeting",
  "Video Recording",
  "PHOTA File Submission",
  "PHOTA Approval",
  "Sehat Card Approval",
  "Admission",
  "Transplant Procedure"
];